nginx-common/src/ngx_live_kmp.h, nginx-kmp-cc-module/src/ngx_stream_kmp_cc_module.c, nginx-kmp-in-module/src/ngx_kmp_in.c, nginx-kmp-out-module/src/ngx_kmp_out_track.c, nginx-kmp-out-module/src/ngx_kmp_out_track.h, nginx-kmp-out-module/src/ngx_kmp_out_track_internal.h, nginx-kmp-out-module/src/ngx_kmp_out_upstream.c
when publishing subtitles over kmp, there may long periods of time where no subtitle line is being sent. by default, the kmp receiver closes idle connections after 20 sec.
to prevent it from closing the connection, the subtitle sender (e.g. kmp-cc-module) can now send 'null packets' periodically. these packets are ignored by the receiver, and used only for preventing the idle timeout from expiring.
kmp-cc-module now sends null packets every 10 sec by default.
=> ngx-kmp-in/out: support null packets

nginx-kmp-in-module/src/ngx_kmp_in.c, nginx-mpegts-module/src/ngx_stream_ts_module.c, nginx-rtmp-module/src/ngx_rtmp.h, nginx-rtmp-module/src/ngx_rtmp_handler.c, nginx-rtmp-module/src/ngx_rtmp_handshake.c, nginx-rtmp-module/src/ngx_rtmp_init.c
avoid generating empty files on connections that do not recv any data (can happen due to load balancer tcp health check)
=> ngx-kmp-in/ts/rtmp: open dump file after recv

nginx-kmp-out-module/src/ngx_kmp_out_track.c, nginx-kmp-out-module/src/ngx_kmp_out_track_internal.h
ngx_kmp_out_track_write_marker_end always calls ngx_kmp_out_track_send_all, but most of the time, no buffer was added to the busy chain of the upstreams.
in ngx_kmp_out_track_write_chain this was already handled by the use of a local 'send' flag.
this change extends this flag also to chunked frame writes.
=> ngx-kmp-out: avoid empty send

nginx-live-module/src/ngx_live_core_module.c, nginx-live-module/src/ngx_live_segmenter.c, nginx-live-module/src/ngx_live_segmenter_ll.c, nginx-live-module/test/tests/input_delay_mem_limit.py, nginx-live-module/test/tests/ll_input_delay_mem_limit.py
safety mechanism to prevent failing on memory limit if input delay is set too high.
=> ngx-live: reduce input delay on mem watermark

nginx-live-module/src/persist/ngx_live_persist_media.c
when aborting media persist due to low memory. ctx.scope.min_index / max_index are used in the error label.
=> ngx-live: fix uninitialized var access

nginx-kmp-cc-module/src/ngx_http_kmp_cc_api_module.c, nginx-live-module/src/http/ngx_http_live_api_module.c, nginx-mpegts-kmp-module/src/ngx_ts_kmp_api_module.c, nginx-rtmp-kmp-module/src/ngx_rtmp_kmp_api_module.c
include the route header after the impl of the route handlers, to avoid the need for prototypes
=> ngx-kmp-cc/ts-kmp/rtmp-kmp: align route defs

nginx-kmp-cc-module/src/media/cea708.c
- Carriage Return - according to spec - Carriage Return (CR) moves the current entry point to the beginning of the next row. If the next row is below the visible window, the window “rolls up”...
The previous impl would not scroll if the number of rows is below the
limit, even when the next line is outside the window.
- Forward - use the actual window size (i_row_count/i_col_count) instead of the max window size
- EXT1 - fixed skipping of variable length codes (0x90-0x9f)
- style touchups
=> ngx-kmp-cc: 708 fixes according to spec

nginx-common/config, nginx-kmp-cc-module/config, nginx-kmp-in-module/config, nginx-kmp-out-module/config, nginx-kmp-rtmp-module/config, nginx-live-module/config, nginx-mpegts-kmp-module/config, nginx-mpegts-module/config, nginx-pckg-module/config, nginx-rtmp-kmp-module/config, nginx-rtmp-module/config
avoid adding include dir more than once, always go through local vars, reset unused params (e.g. ngx_module_libs) etc.
=> nginx build files alignment

nginx-live-module/src/http/ngx_http_live_api_module.c, nginx-live-module/src/ngx_live_input_bufs.c, nginx-live-module/src/ngx_live_segment_cache.h
- api: allow timeline.get on blocked channels
- input bufs: use the mem_used macro instead of nbuffers * size
- segment cache: remove unneeded constant
=> ngx-live: small touchups

conf/controller.php, nginx-kmp-out-module/README.md, nginx-kmp-out-module/src/ngx_kmp_out_upstream.c, nginx-kmp-out-module/src/ngx_kmp_out_upstream.h, nginx-kmp-out-module/src/ngx_kmp_out_upstream_json.h, nginx-kmp-out-module/src/ngx_kmp_out_upstream_json.txt
in preparation for adding an option to start sending from the last frame that was written.
=> ngx-kmp-out: change auto_ack to resume_from enum

nginx-kmp-out-module/src/ngx_kmp_out_track.c
send unpublish notification only if a publish request was sent, or a publish json was provided directly
=> kmp-out: avoid sending unpublish w/o publish

nginx-common/src/ngx_ksmp.h, nginx-live-module/src/persist/ngx_live_persist_serve.c, nginx-pckg-module/src/ngx_http_pckg_m3u8.c, nginx-pckg-module/src/ngx_pckg_ksmp.c, nginx-pckg-module/src/ngx_pckg_ksmp.h
according to spec when the msn/last-part of a rendition report matches the current track, the specific property may be omitted, the rendition report tag should remain.
=> ngx-live/pckg: fix rendition report handling

nginx-kmp-out-module/src/ngx_kmp_out_track.c, nginx-kmp-out-module/src/ngx_kmp_out_track_internal.h, nginx-kmp-out-module/src/ngx_kmp_out_upstream.c
when the frames that are written to the kmp-out-track are written in parts (=using the frame_start / frame_end funcs), append is called before the frame header was written (frame_start writes a zero frame header, and frame_end updates it)
the 'written' value of the track includes the partial frame data that was already written, so ngx_kmp_out_upstream_auto_ack tries to parse it. however, since the frame header is zero, ngx_kmp_out_upstream_ack_packet sees packet_type = 0 and fails.
the solution is to keep the 'written' value when the last frame ended, and auto ack frames up to this value. this way, the header of the partial frame will not be read, and no error will occur.
=> ngx-kmp-out: last_written bug fix

nginx-kmp-out-module/src/ngx_kmp_out_track.c, nginx-kmp-out-module/src/ngx_kmp_out_upstream.c, nginx-kmp-out-module/src/ngx_kmp_out_upstream.h
when the kmp-out-upstream is connected, the auto ack is limited by the number of sent bytes. if the upstream server is receiving very slowly, this may prevent the "watermark" mechanism from freeing buffers. eventually, the memory limit will be hit, and the client rtmp/mpegts connection will be dropped.
note that if the upstream is not receiving at all, the write timeout will kill the connection, the memory limit may be hit only if the upstream server is receiving, but slowly.
the solution is to perform a republish in this case, the republish closes the upstream connection, making it possible to acknowledge packets that were not sent yet.
=> ngx-kmp-out: protect against slow upstream

nginx-kmp-cc-module/src/ngx_stream_kmp_cc_module.c, nginx-kmp-out-module/src/ngx_kmp_out_track.c, nginx-kmp-out-module/src/ngx_kmp_out_track.h, nginx-kmp-out-module/src/ngx_kmp_out_upstream.c, nginx-kmp-out-module/src/ngx_kmp_out_upstream.h, nginx-mpegts-kmp-module/src/ngx_http_ts_kmp_module.c, nginx-mpegts-kmp-module/src/ngx_stream_ts_kmp_module.c, nginx-rtmp-kmp-module/src/ngx_rtmp_kmp_module.c
1. use ngx_current_msec for the republish delay instead of ngx_time, for more accurate timing of republish requests
2. if the connection with the upstream was not established at all, ngx_kmp_out_upstream_republish would incorrectly assume there is nothing to send (u->busy is null). need to check also u->last (u->busy is always null when u->last is null)
3. due to the previous item, the republishes counter may have not counted some republish attempts, increase the default limit to 15 as a safety measure
=> ngx-kmp-out: republish fixes

nginx-rtmp-module/README.md, nginx-rtmp-module/src/ngx_rtmp_live_module.c
- return error in 'play' callback
- return error in case a publisher needs to send data to subscribers
- remove conf directives that are no longer relevant
=> ngx-rtmp: disable play functionality

nginx-rtmp-module/src/ngx_rtmp_codec_module.c
doesn't have to be 0x67, can also be 0x27.
need to extract the nal type using & 0x1f, and compare to 7.
=> ngx-rtmp: fix sps nal check

conf/controller.php, nginx-kmp-out-module/README.md, nginx-kmp-out-module/src/ngx_kmp_out_upstream.c, nginx-kmp-out-module/src/ngx_kmp_out_upstream.h, nginx-kmp-out-module/src/ngx_kmp_out_upstream_json.h, nginx-kmp-out-module/src/ngx_kmp_out_upstream_json.txt
when set to false, upstream errors are ignored, unless the upstream is the last on the output track
=> ngx-kmp-out: add required flag to upstream

nginx-live-module/README.md, nginx-live-module/src/ngx_live_media_info.c
count the number of segments copied to/from each track
=> ngx-live-media-info: add gap filling stats

nginx-common/test/validate_json_write.py, nginx-kmp-out-module/src/ngx_kmp_out_track.c, nginx-live-module/src/ngx_live_media_info.c, nginx-pckg-module/src/ngx_http_pckg_mpd.c
code generated by generate_json_header.py is guaranteed to be consistent between the 'write' func and the 'get_size' func.
however, hand-written code may get out of sync.
the script collects all strings written using ngx_copy_fix, and makes sure the code contains a matching sizeof.
=> ngx-common: add validation on json writes

nginx-pckg-module/src/media/mp4/mp4_muxer.c
=> ngx-pckg-mp4: avoid negative timestamps

nginx-live-module/test/tests/ref/multi_audio_codec-hls-fmp4.txt, nginx-live-module/test/tests/ref/multi_audio_codec_no_video-hls-fmp4.txt
no longer printing the extra data descriptor in esds
=> ngx-live: update tests following mp3 fmp4 change

nginx-kmp-in-module/src/ngx_kmp_in.c, nginx-kmp-in-module/src/ngx_kmp_in.h, nginx-kmp-in-module/src/ngx_kmp_in_json.h, nginx-kmp-in-module/src/ngx_kmp_in_json.txt
in subtitle frames, the pts_delay holds the duration of the cue, a negative pts_delay is meaningless
=> ngx-kmp-in: skip subtitle frames with pts_delay<=0

nginx-kmp-out-module/src/ngx_kmp_out_track.c
when the publish response contains an empty upstreams array, the data written to the kmp output track is silently discarded
=> ngx-kmp-out: fix empty upstreams array in publish

nginx-kmp-out-module/src/ngx_kmp_out_upstream.c
must copy 'acked_bytes' as well, otherwise when auto-acking packets, the module may try to read beyond the last packet that was written.
=> ngx-kmp-out-upstream: copy upstream bugfix

nginx-kmp-out-module/src/ngx_kmp_out_track.c, nginx-live-module/src/ngx_live_segmenter.c
also updated kmp-out to output frame flags in hex
=> ngx-live: log the flags in 'invalid duration'

nginx-live-module/src/ngx_live_segmenter.c, nginx-live-module/src/ngx_live_segmenter_ll.c
unlike video/audio, subtitles are not expected to be continuous - it is possible that subtitles cues will be distributed sparsely. when an inactive event is sent, the syncer module resets itself, and outputs several log lines.
the main reason for avoiding the inactive event for subtitles is to remove this clutter from the log.
=> ngx-live: avoid sending inactive events for subs

transcoder/config.json, transcoder/config_v.json, transcoder/debug/file_streamer.c, transcoder/receiver_server.c, transcoder/transcode/transcode_session.c, transcoder/utils/utils.c, transcoder/utils/utils.h
ffmpeg decoder produce wrong timestamps when there is a jump backwards.
except for being out of sync with ingest , in the case of audio resampler async set to non zero value it will chop off all incoming streram by said amount thus causing missing audio pieces for the duration of the jump.
=> LIV-1191: fix RTMP timestamp restart

transcoder/debug/file_streamer.c, transcoder/utils/time_estimator.c
* use abs(dts - sample.dts) as min function
* fix file_streamer.c created time during ts jump
=> LIV-1206: Transcoded outputs calculate wrong values of 'created' causing packager to break and disconnect

transcoder/common/json_parser.c, transcoder/config_v.json, transcoder/debug/file_streamer.c, transcoder/receiver_server.c, transcoder/tests/config_a.json, transcoder/tests/config_v.json, transcoder/utils/logger.h, transcoder/utils/samples_stats.c, transcoder/utils/samples_stats.h, transcoder/utils/throttler.c, transcoder/utils/throttler.h
- add throttler.h,c
- define config throttler.maxDataRate as max limit on transcoder usage.
* measured in times x normal fps. e.g. if maxDataRate = 2 we expect no more than twice the original throughput.
* By default maxDataRate is set to Infinity and no data rate limit is performed.
- define throttler.useStatsDataRate , bool (defaults: false) as a fallback suggesting use of stream times when estimating data rate. By default, given known fps (or packet per seconds, pps)  throttler won't use dts'es as unreliable and calculate the rate from given target fps. **NOTE**: There are audio codecs like opus, where fps is not known and requires parsing packet header to determine actual number of audio samples, thus complicating the rate calculation.On the other hand, given aac is used most of the …
=> LIV-1205: Transcoder overload protection.

transcoder/utils/throttler.c, transcoder/utils/throttler.h
Currently, only valid fps values trigger throttler action. Badly formed streams are just as easily can cause GPU over utilization, therefore:
- add default fps for video and sampling rate for audio to limit throttler when no actual fps is available
=> Prevent GPU over utilization in case of mis-configured streams with fps not set

transcoder/transcode/transcode_codec.c
=> remove hex_dump call 

nginx-rtmp-module/src/ngx_rtmp_codec_module.c
make sure to only parse audio config data when needed
=> LIV-1259: audio stream transcoding fails due to low memory on packager & ingest server

nginx-mpegts-module/src/ngx_ts_stream.c, nginx-mpegts-module/src/ngx_ts_stream.h
when streaming with SRT some mpegts packets may drop, these errors are
currently silently ignored.
the fix is to use only payload-unit-start-indicator to split the PES
packets, and validate the resulting size against the len stated in the
PES header.
drop the packet also in case of continuity counter mismatch.
=> ngx-mpegts: drop corrupt PES packets

nginx-kmp-out-module/src/ngx_kmp_out_track.c, nginx-kmp-out-module/src/ngx_kmp_out_track.h, nginx-pckg-module/src/media/mpegts/mpegts_muxer.c, nginx-rtmp-kmp-module/README.md, nginx-rtmp-kmp-module/src/ngx_rtmp_kmp_module.c, nginx-rtmp-kmp-module/src/ngx_rtmp_kmp_track.c
to compensate for loss of precision due to RTMP timescale, causing ticking noises in Apple players
=> ngx-rtmp-kmp: sync audio frames timestamps

nginx-pckg-module/src/media/mpegts/mpegts_muxer.c, nginx-rtmp-kmp-module/src/ngx_rtmp_kmp_track.c
- set DEFAULT_PES_HEADER_FREQ back to 8
- remove debug log line in ngx_rtmp_kmp_track_sync_audio
=> revert test and debug changes added to erank branch

nginx-pckg-module/src/media/codec_config.c, nginx-pckg-module/src/media/mpegts/adts_encoder_filter.c
handle HE-AAC audio config in packager module.
**description::**
Bad HLS/ts stream was generated for source flavor (transcoded streams were re-encoded to AAC-LC) due to mp4a config insufficient parsing.
For the same reason, recording generated from mpegts chunks contained bad mp4a config.  As a result, picky media players such as quicktime player based on CoreAudio, refused to play back recorded files
=> SUP-43286: Kaltura Event recordings cannot be imported to Adobe Premiere Pro due to "Unsupported Compression Type"

transcoder/utils/time_estimator.c
Executive Summary  
On September 23, 2025, the Kaltura Media Framework experienced a critical failure with "ngx_buf_queue_get:
memory limit exceeded" at 21:51:45. Our investigation revealed a cascading failure triggered by a bug in
the transcoder's time estimation algorithm during a 90kHz timestamp wraparound event.
Timeline of Discovery
Initial Investigation
- Symptom: Memory buffer exhaustion causing stream processing failure
- Channel: nvp1-1_yqgk4a0v
- Error: "ngx_buf_queue_get: memory limit exceeded"
Root Cause Chain Discovered
1. Timestamp wraparound occurs every ~26.5 hours (90kHz clock cycle)
2. Transcoder time estimator bug creates future timestamps
3. Sync system chaos due to timeline divergence
4. Segmentation failure prevents segment completion
5. Buffer accumulation without …
=> transcoder may deliver kmp frame created time in far future due to wrong clock estimation in transcoded output
