kaltura/media-framework

nginx-kmp-cc-module/src/ngx_kmp_cc.c

also removed the check for em_data == 0xff - the value of this field is not defined by the spec, ffmpeg outputs 0

ngx-kmp-cc: support hevc input

---

nginx-common/scripts/generate_json_header.py
nginx-kmp-out-module/src/ngx_kmp_out_track_json.h
nginx-kmp-out-module/src/ngx_kmp_out_track_json.txt
nginx-live-module/src/ngx_live_media_info_json.h
nginx-live-module/src/ngx_live_media_info_json.txt
nginx-live-module/src/persist/ngx_live_persist_json.h
nginx-live-module/src/persist/ngx_live_persist_json.txt
nginx-mpegts-kmp-module/src/ngx_ts_kmp_api_json.txt

avoid unneeded ifs to remove the comma in case the function doesn't
write anything (p = next == p ? p - 1 : next;)

gen_json_header: add non-empty func (neFunc)

---

nginx-pckg-module/src/ngx_http_pckg_m3u8.c

when enabled (default) #EXT-X-PROGRAM-DATE-TIME tags will be returned in index playlists.

ngx-pckg-m3u8: pckg_m3u8_program_date_time flag

---

nginx-live-module/src/ngx_live_segment_cache.c

can be used to calc the % of segment requests served from cache vs persist

ngx-live: add stats for segment cache reads

---

nginx-live-module/test/test_base.py
nginx-live-module/test/tests/dash_escape_strings.py
nginx-live-module/test/tests/ref/dash_escape_strings-dash.txt
nginx-pckg-module/src/ngx_http_pckg_mpd.c

- profiles
- label
- lang
- cea params

ngx-pckg-mpd: add xml escape to relevant fields

---

nginx-kmp-rtmp-module/src/ngx_http_kmp_rtmp_api_module.c
nginx-kmp-rtmp-module/src/ngx_http_kmp_rtmp_api_routes.h
nginx-kmp-rtmp-module/src/ngx_http_kmp_rtmp_api_routes.txt
nginx-kmp-rtmp-module/src/ngx_kmp_rtmp.h
nginx-kmp-rtmp-module/src/ngx_kmp_rtmp_upstream_json.h
nginx-kmp-rtmp-module/src/ngx_kmp_rtmp_upstream_json.txt

GET /upstreams/%
GET /upstreams/%/streams
LIST /upstreams/%/streams

ngx-kmp-rtmp: add info api routes

---

conf/README.md
nginx-common/src/ngx_http_api.c
nginx-common/src/ngx_json_parser.c
nginx-common/src/ngx_json_parser.h

php by default escapes / in json encode

ngx-http-api: add json decode of uri

---

conf/README.md
conf/build.sh

avoid duplicating the nginx configure command in the readme

sample-conf: add build script

---

conf/controller.php
conf/transcoder.json
transcoder/README.md

command line args, conf structure, control endpoints

transcoder: add documentation

---

README.md
nginx-kmp-cc-module/README.md
nginx-live-module/README.md
nginx-mpegts-kmp-module/README.md
nginx-rtmp-kmp-module/README.md

- debug macros
- active policy
- filler etc.

doc: add additional details

---

nginx-kmp-cc-module/README.md
nginx-kmp-cc-module/src/ngx_stream_kmp_cc_module.c
nginx-kmp-in-module/src/ngx_kmp_in.c
nginx-kmp-in-module/src/ngx_kmp_in.h
nginx-kmp-out-module/src/ngx_kmp_out_track.c
nginx-kmp-out-module/src/ngx_kmp_out_track.h
nginx-kmp-rtmp-module/README.md
nginx-kmp-rtmp-module/src/ngx_stream_kmp_rtmp_module.c
nginx-live-module/README.md
nginx-live-module/src/stream/ngx_stream_live_kmp_module.c
nginx-mpegts-kmp-module/README.md
nginx-mpegts-kmp-module/src/ngx_http_ts_kmp_module.c
nginx-mpegts-kmp-module/src/ngx_stream_ts_kmp_module.c
nginx-rtmp-kmp-module/README.md
nginx-rtmp-kmp-module/src/ngx_rtmp_kmp_module.c

kmp-in-out: change log_frames option to enum

---

nginx-common/src/ngx_live_kmp.h
nginx-kmp-in-module/src/ngx_kmp_in.c
nginx-kmp-out-module/README.md
nginx-kmp-out-module/src/ngx_kmp_out_track.c
nginx-kmp-out-module/src/ngx_kmp_out_upstream.c
nginx-kmp-out-module/src/ngx_kmp_out_upstream.h
nginx-kmp-out-module/src/ngx_kmp_out_upstream_json.h
nginx-kmp-out-module/src/ngx_kmp_out_upstream_json.txt
nginx-live-module/src/ngx_live_segmenter.c
nginx-live-module/src/ngx_live_segmenter_ll.c

also moved kmp connect/ack frames fields to a separate struct

ngx-kmp-out: add last_written resume_from option

---

nginx-common/test/json_pretty/test.py
nginx-common/test/validate_config_files.py
nginx-common/test/validate_directives_doc.py
nginx-common/test/validate_logs.py
nginx-kmp-cc-module/README.md
nginx-kmp-in-module/src/ngx_kmp_in.c
nginx-kmp-out-module/src/ngx_kmp_out_track.c
nginx-live-module/src/http/ngx_http_live_api_module.c
nginx-mpegts-kmp-module/README.md
nginx-mpegts-module/README.md
nginx-pckg-module/README.md
nginx-rtmp-module/README.md
nginx-rtmp-module/src/ngx_rtmp_codec_module.c
nginx-rtmp-module/src/ngx_rtmp_core_module.c

- check config file deps
- validate directives doc
- validate log lines

nginx-common: add static analysis

---

nginx-live-module/src/persist/ngx_live_persist_json.h
nginx-live-module/src/persist/ngx_live_persist_json.txt
nginx-live-module/src/persist/ngx_live_persist_media.c
nginx-live-module/src/persist/ngx_live_persist_media.h

ngx-live: persist-media add success-index stat

---

nginx-live-module/README.md
nginx-live-module/src/ngx_live_segment_list.c
nginx-live-module/src/ngx_live_segment_list.h
nginx-live-module/test/tests/long_stream.py

total number of nodes, elements, segments

ngx-live: add more segment list stats

---

nginx-pckg-module/README.md
nginx-pckg-module/src/media/mp4/mp4_init_segment.c
nginx-pckg-module/src/ngx_pckg_ksmp.c

also fixed ac3/ec3 with fmp4 container (need to output dac3/dec3 box in stsd instead of esds)

ngx-pckg: support opus audio codec

---

nginx-common/test/common.py
nginx-common/test/validate_api_doc.py
nginx-common/test/validate_config_files.py
nginx-common/test/validate_directives_doc.py
nginx-common/test/validate_json_write.py
nginx-common/test/validate_logs.py

- replace printErr -> report_err
- add a func for getting the base dir

common-test: touch ups

---

nginx-live-module/src/ngx_live_segment_cache.c

when freeing buffers, need to use the oldest segment that is not empty

ngx-live: empty segment bugfix

---

conf/README.md

in order to refresh the loader cache

sample-conf: add ldconfig after install libsrt

---

nginx-rtmp-kmp-module/Dockerfile

https://github.com/Haivision/srt/releases/tag/v1.5.3

Fix srt version to 1.5.3

---

nginx-kmp-cc-module/src/media/cea708.c

need to output if any of the windows becomes visible, should not be only according to the last one toggled

ngx-kmp-cc bug fix
